export interface City {
  id: string;
  name: string;
  nameEn: string;
  country: string;
  countryCode: string;
  timezone: string;
  flag: string;
}

export const CITIES: City[] = [
  // ===== ASIA =====
  // Japan
  {
    id: "tokyo",
    name: "東京",
    nameEn: "Tokyo",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "osaka",
    name: "大阪",
    nameEn: "Osaka",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "nagoya",
    name: "名古屋",
    nameEn: "Nagoya",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "sapporo",
    name: "札幌",
    nameEn: "Sapporo",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "fukuoka",
    name: "福岡",
    nameEn: "Fukuoka",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "kyoto",
    name: "京都",
    nameEn: "Kyoto",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "yokohama",
    name: "横浜",
    nameEn: "Yokohama",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "kobe",
    name: "神戸",
    nameEn: "Kobe",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "sendai",
    name: "仙台",
    nameEn: "Sendai",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "hiroshima",
    name: "広島",
    nameEn: "Hiroshima",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },
  {
    id: "naha",
    name: "那覇",
    nameEn: "Naha",
    country: "日本",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    flag: "🇯🇵",
  },

  // Korea
  {
    id: "seoul",
    name: "ソウル",
    nameEn: "Seoul",
    country: "韓国",
    countryCode: "KR",
    timezone: "Asia/Seoul",
    flag: "🇰🇷",
  },
  {
    id: "busan",
    name: "釜山",
    nameEn: "Busan",
    country: "韓国",
    countryCode: "KR",
    timezone: "Asia/Seoul",
    flag: "🇰🇷",
  },
  {
    id: "incheon",
    name: "仁川",
    nameEn: "Incheon",
    country: "韓国",
    countryCode: "KR",
    timezone: "Asia/Seoul",
    flag: "🇰🇷",
  },
  {
    id: "pyongyang",
    name: "平壌",
    nameEn: "Pyongyang",
    country: "北朝鮮",
    countryCode: "KP",
    timezone: "Asia/Pyongyang",
    flag: "🇰🇵",
  },

  // China
  {
    id: "beijing",
    name: "北京",
    nameEn: "Beijing",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "shanghai",
    name: "上海",
    nameEn: "Shanghai",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "guangzhou",
    name: "広州",
    nameEn: "Guangzhou",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "shenzhen",
    name: "深圳",
    nameEn: "Shenzhen",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "chengdu",
    name: "成都",
    nameEn: "Chengdu",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "xian",
    name: "西安",
    nameEn: "Xi'an",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "hangzhou",
    name: "杭州",
    nameEn: "Hangzhou",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "nanjing",
    name: "南京",
    nameEn: "Nanjing",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "wuhan",
    name: "武漢",
    nameEn: "Wuhan",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "chongqing",
    name: "重慶",
    nameEn: "Chongqing",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "tianjin",
    name: "天津",
    nameEn: "Tianjin",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "dalian",
    name: "大連",
    nameEn: "Dalian",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "qingdao",
    name: "青島",
    nameEn: "Qingdao",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Shanghai",
    flag: "🇨🇳",
  },
  {
    id: "urumqi",
    name: "ウルムチ",
    nameEn: "Urumqi",
    country: "中国",
    countryCode: "CN",
    timezone: "Asia/Urumqi",
    flag: "🇨🇳",
  },
  {
    id: "hong-kong",
    name: "香港",
    nameEn: "Hong Kong",
    country: "香港",
    countryCode: "HK",
    timezone: "Asia/Hong_Kong",
    flag: "🇭🇰",
  },
  {
    id: "macau",
    name: "マカオ",
    nameEn: "Macau",
    country: "マカオ",
    countryCode: "MO",
    timezone: "Asia/Macau",
    flag: "🇲🇴",
  },

  // Taiwan
  {
    id: "taipei",
    name: "台北",
    nameEn: "Taipei",
    country: "台湾",
    countryCode: "TW",
    timezone: "Asia/Taipei",
    flag: "🇹🇼",
  },
  {
    id: "kaohsiung",
    name: "高雄",
    nameEn: "Kaohsiung",
    country: "台湾",
    countryCode: "TW",
    timezone: "Asia/Taipei",
    flag: "🇹🇼",
  },

  // Southeast Asia
  {
    id: "singapore",
    name: "シンガポール",
    nameEn: "Singapore",
    country: "シンガポール",
    countryCode: "SG",
    timezone: "Asia/Singapore",
    flag: "🇸🇬",
  },
  {
    id: "bangkok",
    name: "バンコク",
    nameEn: "Bangkok",
    country: "タイ",
    countryCode: "TH",
    timezone: "Asia/Bangkok",
    flag: "🇹🇭",
  },
  {
    id: "chiang-mai",
    name: "チェンマイ",
    nameEn: "Chiang Mai",
    country: "タイ",
    countryCode: "TH",
    timezone: "Asia/Bangkok",
    flag: "🇹🇭",
  },
  {
    id: "phuket",
    name: "プーケット",
    nameEn: "Phuket",
    country: "タイ",
    countryCode: "TH",
    timezone: "Asia/Bangkok",
    flag: "🇹🇭",
  },
  {
    id: "hanoi",
    name: "ハノイ",
    nameEn: "Hanoi",
    country: "ベトナム",
    countryCode: "VN",
    timezone: "Asia/Ho_Chi_Minh",
    flag: "🇻🇳",
  },
  {
    id: "ho-chi-minh",
    name: "ホーチミン",
    nameEn: "Ho Chi Minh City",
    country: "ベトナム",
    countryCode: "VN",
    timezone: "Asia/Ho_Chi_Minh",
    flag: "🇻🇳",
  },
  {
    id: "da-nang",
    name: "ダナン",
    nameEn: "Da Nang",
    country: "ベトナム",
    countryCode: "VN",
    timezone: "Asia/Ho_Chi_Minh",
    flag: "🇻🇳",
  },
  {
    id: "kuala-lumpur",
    name: "クアラルンプール",
    nameEn: "Kuala Lumpur",
    country: "マレーシア",
    countryCode: "MY",
    timezone: "Asia/Kuala_Lumpur",
    flag: "🇲🇾",
  },
  {
    id: "penang",
    name: "ペナン",
    nameEn: "Penang",
    country: "マレーシア",
    countryCode: "MY",
    timezone: "Asia/Kuala_Lumpur",
    flag: "🇲🇾",
  },
  {
    id: "jakarta",
    name: "ジャカルタ",
    nameEn: "Jakarta",
    country: "インドネシア",
    countryCode: "ID",
    timezone: "Asia/Jakarta",
    flag: "🇮🇩",
  },
  {
    id: "bali",
    name: "バリ",
    nameEn: "Bali",
    country: "インドネシア",
    countryCode: "ID",
    timezone: "Asia/Makassar",
    flag: "🇮🇩",
  },
  {
    id: "surabaya",
    name: "スラバヤ",
    nameEn: "Surabaya",
    country: "インドネシア",
    countryCode: "ID",
    timezone: "Asia/Jakarta",
    flag: "🇮🇩",
  },
  {
    id: "manila",
    name: "マニラ",
    nameEn: "Manila",
    country: "フィリピン",
    countryCode: "PH",
    timezone: "Asia/Manila",
    flag: "🇵🇭",
  },
  {
    id: "cebu",
    name: "セブ",
    nameEn: "Cebu",
    country: "フィリピン",
    countryCode: "PH",
    timezone: "Asia/Manila",
    flag: "🇵🇭",
  },
  {
    id: "phnom-penh",
    name: "プノンペン",
    nameEn: "Phnom Penh",
    country: "カンボジア",
    countryCode: "KH",
    timezone: "Asia/Phnom_Penh",
    flag: "🇰🇭",
  },
  {
    id: "siem-reap",
    name: "シェムリアップ",
    nameEn: "Siem Reap",
    country: "カンボジア",
    countryCode: "KH",
    timezone: "Asia/Phnom_Penh",
    flag: "🇰🇭",
  },
  {
    id: "vientiane",
    name: "ビエンチャン",
    nameEn: "Vientiane",
    country: "ラオス",
    countryCode: "LA",
    timezone: "Asia/Vientiane",
    flag: "🇱🇦",
  },
  {
    id: "yangon",
    name: "ヤンゴン",
    nameEn: "Yangon",
    country: "ミャンマー",
    countryCode: "MM",
    timezone: "Asia/Yangon",
    flag: "🇲🇲",
  },
  {
    id: "brunei",
    name: "バンダルスリブガワン",
    nameEn: "Bandar Seri Begawan",
    country: "ブルネイ",
    countryCode: "BN",
    timezone: "Asia/Brunei",
    flag: "🇧🇳",
  },
  {
    id: "dili",
    name: "ディリ",
    nameEn: "Dili",
    country: "東ティモール",
    countryCode: "TL",
    timezone: "Asia/Dili",
    flag: "🇹🇱",
  },

  // South Asia
  {
    id: "mumbai",
    name: "ムンバイ",
    nameEn: "Mumbai",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "new-delhi",
    name: "ニューデリー",
    nameEn: "New Delhi",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "bangalore",
    name: "バンガロール",
    nameEn: "Bangalore",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "chennai",
    name: "チェンナイ",
    nameEn: "Chennai",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "kolkata",
    name: "コルカタ",
    nameEn: "Kolkata",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "hyderabad",
    name: "ハイデラバード",
    nameEn: "Hyderabad",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "ahmedabad",
    name: "アーメダバード",
    nameEn: "Ahmedabad",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "pune",
    name: "プネー",
    nameEn: "Pune",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "jaipur",
    name: "ジャイプール",
    nameEn: "Jaipur",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "goa",
    name: "ゴア",
    nameEn: "Goa",
    country: "インド",
    countryCode: "IN",
    timezone: "Asia/Kolkata",
    flag: "🇮🇳",
  },
  {
    id: "dhaka",
    name: "ダッカ",
    nameEn: "Dhaka",
    country: "バングラデシュ",
    countryCode: "BD",
    timezone: "Asia/Dhaka",
    flag: "🇧🇩",
  },
  {
    id: "karachi",
    name: "カラチ",
    nameEn: "Karachi",
    country: "パキスタン",
    countryCode: "PK",
    timezone: "Asia/Karachi",
    flag: "🇵🇰",
  },
  {
    id: "lahore",
    name: "ラホール",
    nameEn: "Lahore",
    country: "パキスタン",
    countryCode: "PK",
    timezone: "Asia/Karachi",
    flag: "🇵🇰",
  },
  {
    id: "islamabad",
    name: "イスラマバード",
    nameEn: "Islamabad",
    country: "パキスタン",
    countryCode: "PK",
    timezone: "Asia/Karachi",
    flag: "🇵🇰",
  },
  {
    id: "colombo",
    name: "コロンボ",
    nameEn: "Colombo",
    country: "スリランカ",
    countryCode: "LK",
    timezone: "Asia/Colombo",
    flag: "🇱🇰",
  },
  {
    id: "kathmandu",
    name: "カトマンズ",
    nameEn: "Kathmandu",
    country: "ネパール",
    countryCode: "NP",
    timezone: "Asia/Kathmandu",
    flag: "🇳🇵",
  },
  {
    id: "thimphu",
    name: "ティンプー",
    nameEn: "Thimphu",
    country: "ブータン",
    countryCode: "BT",
    timezone: "Asia/Thimphu",
    flag: "🇧🇹",
  },
  {
    id: "male",
    name: "マレ",
    nameEn: "Male",
    country: "モルディブ",
    countryCode: "MV",
    timezone: "Indian/Maldives",
    flag: "🇲🇻",
  },

  // Central Asia
  {
    id: "almaty",
    name: "アルマトイ",
    nameEn: "Almaty",
    country: "カザフスタン",
    countryCode: "KZ",
    timezone: "Asia/Almaty",
    flag: "🇰🇿",
  },
  {
    id: "astana",
    name: "アスタナ",
    nameEn: "Astana",
    country: "カザフスタン",
    countryCode: "KZ",
    timezone: "Asia/Almaty",
    flag: "🇰🇿",
  },
  {
    id: "tashkent",
    name: "タシケント",
    nameEn: "Tashkent",
    country: "ウズベキスタン",
    countryCode: "UZ",
    timezone: "Asia/Tashkent",
    flag: "🇺🇿",
  },
  {
    id: "samarkand",
    name: "サマルカンド",
    nameEn: "Samarkand",
    country: "ウズベキスタン",
    countryCode: "UZ",
    timezone: "Asia/Samarkand",
    flag: "🇺🇿",
  },
  {
    id: "bishkek",
    name: "ビシュケク",
    nameEn: "Bishkek",
    country: "キルギス",
    countryCode: "KG",
    timezone: "Asia/Bishkek",
    flag: "🇰🇬",
  },
  {
    id: "dushanbe",
    name: "ドゥシャンベ",
    nameEn: "Dushanbe",
    country: "タジキスタン",
    countryCode: "TJ",
    timezone: "Asia/Dushanbe",
    flag: "🇹🇯",
  },
  {
    id: "ashgabat",
    name: "アシガバート",
    nameEn: "Ashgabat",
    country: "トルクメニスタン",
    countryCode: "TM",
    timezone: "Asia/Ashgabat",
    flag: "🇹🇲",
  },
  {
    id: "ulaanbaatar",
    name: "ウランバートル",
    nameEn: "Ulaanbaatar",
    country: "モンゴル",
    countryCode: "MN",
    timezone: "Asia/Ulaanbaatar",
    flag: "🇲🇳",
  },

  // Middle East
  {
    id: "dubai",
    name: "ドバイ",
    nameEn: "Dubai",
    country: "アラブ首長国連邦",
    countryCode: "AE",
    timezone: "Asia/Dubai",
    flag: "🇦🇪",
  },
  {
    id: "abu-dhabi",
    name: "アブダビ",
    nameEn: "Abu Dhabi",
    country: "アラブ首長国連邦",
    countryCode: "AE",
    timezone: "Asia/Dubai",
    flag: "🇦🇪",
  },
  {
    id: "doha",
    name: "ドーハ",
    nameEn: "Doha",
    country: "カタール",
    countryCode: "QA",
    timezone: "Asia/Qatar",
    flag: "🇶🇦",
  },
  {
    id: "riyadh",
    name: "リヤド",
    nameEn: "Riyadh",
    country: "サウジアラビア",
    countryCode: "SA",
    timezone: "Asia/Riyadh",
    flag: "🇸🇦",
  },
  {
    id: "jeddah",
    name: "ジッダ",
    nameEn: "Jeddah",
    country: "サウジアラビア",
    countryCode: "SA",
    timezone: "Asia/Riyadh",
    flag: "🇸🇦",
  },
  {
    id: "mecca",
    name: "メッカ",
    nameEn: "Mecca",
    country: "サウジアラビア",
    countryCode: "SA",
    timezone: "Asia/Riyadh",
    flag: "🇸🇦",
  },
  {
    id: "kuwait-city",
    name: "クウェート",
    nameEn: "Kuwait City",
    country: "クウェート",
    countryCode: "KW",
    timezone: "Asia/Kuwait",
    flag: "🇰🇼",
  },
  {
    id: "manama",
    name: "マナーマ",
    nameEn: "Manama",
    country: "バーレーン",
    countryCode: "BH",
    timezone: "Asia/Bahrain",
    flag: "🇧🇭",
  },
  {
    id: "muscat",
    name: "マスカット",
    nameEn: "Muscat",
    country: "オマーン",
    countryCode: "OM",
    timezone: "Asia/Muscat",
    flag: "🇴🇲",
  },
  {
    id: "tehran",
    name: "テヘラン",
    nameEn: "Tehran",
    country: "イラン",
    countryCode: "IR",
    timezone: "Asia/Tehran",
    flag: "🇮🇷",
  },
  {
    id: "baghdad",
    name: "バグダッド",
    nameEn: "Baghdad",
    country: "イラク",
    countryCode: "IQ",
    timezone: "Asia/Baghdad",
    flag: "🇮🇶",
  },
  {
    id: "amman",
    name: "アンマン",
    nameEn: "Amman",
    country: "ヨルダン",
    countryCode: "JO",
    timezone: "Asia/Amman",
    flag: "🇯🇴",
  },
  {
    id: "beirut",
    name: "ベイルート",
    nameEn: "Beirut",
    country: "レバノン",
    countryCode: "LB",
    timezone: "Asia/Beirut",
    flag: "🇱🇧",
  },
  {
    id: "damascus",
    name: "ダマスカス",
    nameEn: "Damascus",
    country: "シリア",
    countryCode: "SY",
    timezone: "Asia/Damascus",
    flag: "🇸🇾",
  },
  {
    id: "jerusalem",
    name: "エルサレム",
    nameEn: "Jerusalem",
    country: "イスラエル",
    countryCode: "IL",
    timezone: "Asia/Jerusalem",
    flag: "🇮🇱",
  },
  {
    id: "tel-aviv",
    name: "テルアビブ",
    nameEn: "Tel Aviv",
    country: "イスラエル",
    countryCode: "IL",
    timezone: "Asia/Jerusalem",
    flag: "🇮🇱",
  },
  {
    id: "sanaa",
    name: "サナア",
    nameEn: "Sanaa",
    country: "イエメン",
    countryCode: "YE",
    timezone: "Asia/Aden",
    flag: "🇾🇪",
  },
  {
    id: "kabul",
    name: "カブール",
    nameEn: "Kabul",
    country: "アフガニスタン",
    countryCode: "AF",
    timezone: "Asia/Kabul",
    flag: "🇦🇫",
  },

  // Caucasus
  {
    id: "baku",
    name: "バクー",
    nameEn: "Baku",
    country: "アゼルバイジャン",
    countryCode: "AZ",
    timezone: "Asia/Baku",
    flag: "🇦🇿",
  },
  {
    id: "tbilisi",
    name: "トビリシ",
    nameEn: "Tbilisi",
    country: "ジョージア",
    countryCode: "GE",
    timezone: "Asia/Tbilisi",
    flag: "🇬🇪",
  },
  {
    id: "yerevan",
    name: "エレバン",
    nameEn: "Yerevan",
    country: "アルメニア",
    countryCode: "AM",
    timezone: "Asia/Yerevan",
    flag: "🇦🇲",
  },

  // ===== EUROPE =====
  // Western Europe
  {
    id: "london",
    name: "ロンドン",
    nameEn: "London",
    country: "イギリス",
    countryCode: "GB",
    timezone: "Europe/London",
    flag: "🇬🇧",
  },
  {
    id: "manchester",
    name: "マンチェスター",
    nameEn: "Manchester",
    country: "イギリス",
    countryCode: "GB",
    timezone: "Europe/London",
    flag: "🇬🇧",
  },
  {
    id: "edinburgh",
    name: "エディンバラ",
    nameEn: "Edinburgh",
    country: "イギリス",
    countryCode: "GB",
    timezone: "Europe/London",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  },
  {
    id: "dublin",
    name: "ダブリン",
    nameEn: "Dublin",
    country: "アイルランド",
    countryCode: "IE",
    timezone: "Europe/Dublin",
    flag: "🇮🇪",
  },
  {
    id: "paris",
    name: "パリ",
    nameEn: "Paris",
    country: "フランス",
    countryCode: "FR",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
  },
  {
    id: "lyon",
    name: "リヨン",
    nameEn: "Lyon",
    country: "フランス",
    countryCode: "FR",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
  },
  {
    id: "marseille",
    name: "マルセイユ",
    nameEn: "Marseille",
    country: "フランス",
    countryCode: "FR",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
  },
  {
    id: "nice",
    name: "ニース",
    nameEn: "Nice",
    country: "フランス",
    countryCode: "FR",
    timezone: "Europe/Paris",
    flag: "🇫🇷",
  },
  {
    id: "amsterdam",
    name: "アムステルダム",
    nameEn: "Amsterdam",
    country: "オランダ",
    countryCode: "NL",
    timezone: "Europe/Amsterdam",
    flag: "🇳🇱",
  },
  {
    id: "rotterdam",
    name: "ロッテルダム",
    nameEn: "Rotterdam",
    country: "オランダ",
    countryCode: "NL",
    timezone: "Europe/Amsterdam",
    flag: "🇳🇱",
  },
  {
    id: "brussels",
    name: "ブリュッセル",
    nameEn: "Brussels",
    country: "ベルギー",
    countryCode: "BE",
    timezone: "Europe/Brussels",
    flag: "🇧🇪",
  },
  {
    id: "luxembourg",
    name: "ルクセンブルク",
    nameEn: "Luxembourg",
    country: "ルクセンブルク",
    countryCode: "LU",
    timezone: "Europe/Luxembourg",
    flag: "🇱🇺",
  },
  {
    id: "monaco",
    name: "モナコ",
    nameEn: "Monaco",
    country: "モナコ",
    countryCode: "MC",
    timezone: "Europe/Monaco",
    flag: "🇲🇨",
  },

  // Central Europe
  {
    id: "berlin",
    name: "ベルリン",
    nameEn: "Berlin",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "munich",
    name: "ミュンヘン",
    nameEn: "Munich",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "frankfurt",
    name: "フランクフルト",
    nameEn: "Frankfurt",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "hamburg",
    name: "ハンブルク",
    nameEn: "Hamburg",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "cologne",
    name: "ケルン",
    nameEn: "Cologne",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "dusseldorf",
    name: "デュッセルドルフ",
    nameEn: "Düsseldorf",
    country: "ドイツ",
    countryCode: "DE",
    timezone: "Europe/Berlin",
    flag: "🇩🇪",
  },
  {
    id: "zurich",
    name: "チューリッヒ",
    nameEn: "Zurich",
    country: "スイス",
    countryCode: "CH",
    timezone: "Europe/Zurich",
    flag: "🇨🇭",
  },
  {
    id: "geneva",
    name: "ジュネーブ",
    nameEn: "Geneva",
    country: "スイス",
    countryCode: "CH",
    timezone: "Europe/Zurich",
    flag: "🇨🇭",
  },
  {
    id: "bern",
    name: "ベルン",
    nameEn: "Bern",
    country: "スイス",
    countryCode: "CH",
    timezone: "Europe/Zurich",
    flag: "🇨🇭",
  },
  {
    id: "vienna",
    name: "ウィーン",
    nameEn: "Vienna",
    country: "オーストリア",
    countryCode: "AT",
    timezone: "Europe/Vienna",
    flag: "🇦🇹",
  },
  {
    id: "salzburg",
    name: "ザルツブルク",
    nameEn: "Salzburg",
    country: "オーストリア",
    countryCode: "AT",
    timezone: "Europe/Vienna",
    flag: "🇦🇹",
  },
  {
    id: "prague",
    name: "プラハ",
    nameEn: "Prague",
    country: "チェコ",
    countryCode: "CZ",
    timezone: "Europe/Prague",
    flag: "🇨🇿",
  },
  {
    id: "warsaw",
    name: "ワルシャワ",
    nameEn: "Warsaw",
    country: "ポーランド",
    countryCode: "PL",
    timezone: "Europe/Warsaw",
    flag: "🇵🇱",
  },
  {
    id: "krakow",
    name: "クラクフ",
    nameEn: "Krakow",
    country: "ポーランド",
    countryCode: "PL",
    timezone: "Europe/Warsaw",
    flag: "🇵🇱",
  },
  {
    id: "budapest",
    name: "ブダペスト",
    nameEn: "Budapest",
    country: "ハンガリー",
    countryCode: "HU",
    timezone: "Europe/Budapest",
    flag: "🇭🇺",
  },
  {
    id: "bratislava",
    name: "ブラチスラバ",
    nameEn: "Bratislava",
    country: "スロバキア",
    countryCode: "SK",
    timezone: "Europe/Bratislava",
    flag: "🇸🇰",
  },
  {
    id: "ljubljana",
    name: "リュブリャナ",
    nameEn: "Ljubljana",
    country: "スロベニア",
    countryCode: "SI",
    timezone: "Europe/Ljubljana",
    flag: "🇸🇮",
  },

  // Southern Europe
  {
    id: "rome",
    name: "ローマ",
    nameEn: "Rome",
    country: "イタリア",
    countryCode: "IT",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
  },
  {
    id: "milan",
    name: "ミラノ",
    nameEn: "Milan",
    country: "イタリア",
    countryCode: "IT",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
  },
  {
    id: "florence",
    name: "フィレンツェ",
    nameEn: "Florence",
    country: "イタリア",
    countryCode: "IT",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
  },
  {
    id: "venice",
    name: "ヴェネツィア",
    nameEn: "Venice",
    country: "イタリア",
    countryCode: "IT",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
  },
  {
    id: "naples",
    name: "ナポリ",
    nameEn: "Naples",
    country: "イタリア",
    countryCode: "IT",
    timezone: "Europe/Rome",
    flag: "🇮🇹",
  },
  {
    id: "vatican",
    name: "バチカン",
    nameEn: "Vatican City",
    country: "バチカン",
    countryCode: "VA",
    timezone: "Europe/Vatican",
    flag: "🇻🇦",
  },
  {
    id: "san-marino",
    name: "サンマリノ",
    nameEn: "San Marino",
    country: "サンマリノ",
    countryCode: "SM",
    timezone: "Europe/San_Marino",
    flag: "🇸🇲",
  },
  {
    id: "madrid",
    name: "マドリード",
    nameEn: "Madrid",
    country: "スペイン",
    countryCode: "ES",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
  },
  {
    id: "barcelona",
    name: "バルセロナ",
    nameEn: "Barcelona",
    country: "スペイン",
    countryCode: "ES",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
  },
  {
    id: "seville",
    name: "セビリア",
    nameEn: "Seville",
    country: "スペイン",
    countryCode: "ES",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
  },
  {
    id: "valencia",
    name: "バレンシア",
    nameEn: "Valencia",
    country: "スペイン",
    countryCode: "ES",
    timezone: "Europe/Madrid",
    flag: "🇪🇸",
  },
  {
    id: "lisbon",
    name: "リスボン",
    nameEn: "Lisbon",
    country: "ポルトガル",
    countryCode: "PT",
    timezone: "Europe/Lisbon",
    flag: "🇵🇹",
  },
  {
    id: "porto",
    name: "ポルト",
    nameEn: "Porto",
    country: "ポルトガル",
    countryCode: "PT",
    timezone: "Europe/Lisbon",
    flag: "🇵🇹",
  },
  {
    id: "andorra",
    name: "アンドラ",
    nameEn: "Andorra la Vella",
    country: "アンドラ",
    countryCode: "AD",
    timezone: "Europe/Andorra",
    flag: "🇦🇩",
  },
  {
    id: "gibraltar",
    name: "ジブラルタル",
    nameEn: "Gibraltar",
    country: "ジブラルタル",
    countryCode: "GI",
    timezone: "Europe/Gibraltar",
    flag: "🇬🇮",
  },
  {
    id: "athens",
    name: "アテネ",
    nameEn: "Athens",
    country: "ギリシャ",
    countryCode: "GR",
    timezone: "Europe/Athens",
    flag: "🇬🇷",
  },
  {
    id: "thessaloniki",
    name: "テッサロニキ",
    nameEn: "Thessaloniki",
    country: "ギリシャ",
    countryCode: "GR",
    timezone: "Europe/Athens",
    flag: "🇬🇷",
  },
  {
    id: "malta",
    name: "バレッタ",
    nameEn: "Valletta",
    country: "マルタ",
    countryCode: "MT",
    timezone: "Europe/Malta",
    flag: "🇲🇹",
  },
  {
    id: "nicosia",
    name: "ニコシア",
    nameEn: "Nicosia",
    country: "キプロス",
    countryCode: "CY",
    timezone: "Asia/Nicosia",
    flag: "🇨🇾",
  },

  // Balkans
  {
    id: "zagreb",
    name: "ザグレブ",
    nameEn: "Zagreb",
    country: "クロアチア",
    countryCode: "HR",
    timezone: "Europe/Zagreb",
    flag: "🇭🇷",
  },
  {
    id: "dubrovnik",
    name: "ドブロブニク",
    nameEn: "Dubrovnik",
    country: "クロアチア",
    countryCode: "HR",
    timezone: "Europe/Zagreb",
    flag: "🇭🇷",
  },
  {
    id: "belgrade",
    name: "ベオグラード",
    nameEn: "Belgrade",
    country: "セルビア",
    countryCode: "RS",
    timezone: "Europe/Belgrade",
    flag: "🇷🇸",
  },
  {
    id: "sarajevo",
    name: "サラエボ",
    nameEn: "Sarajevo",
    country: "ボスニア・ヘルツェゴビナ",
    countryCode: "BA",
    timezone: "Europe/Sarajevo",
    flag: "🇧🇦",
  },
  {
    id: "podgorica",
    name: "ポドゴリツァ",
    nameEn: "Podgorica",
    country: "モンテネグロ",
    countryCode: "ME",
    timezone: "Europe/Podgorica",
    flag: "🇲🇪",
  },
  {
    id: "skopje",
    name: "スコピエ",
    nameEn: "Skopje",
    country: "北マケドニア",
    countryCode: "MK",
    timezone: "Europe/Skopje",
    flag: "🇲🇰",
  },
  {
    id: "tirana",
    name: "ティラナ",
    nameEn: "Tirana",
    country: "アルバニア",
    countryCode: "AL",
    timezone: "Europe/Tirane",
    flag: "🇦🇱",
  },
  {
    id: "pristina",
    name: "プリシュティナ",
    nameEn: "Pristina",
    country: "コソボ",
    countryCode: "XK",
    timezone: "Europe/Belgrade",
    flag: "🇽🇰",
  },
  {
    id: "sofia",
    name: "ソフィア",
    nameEn: "Sofia",
    country: "ブルガリア",
    countryCode: "BG",
    timezone: "Europe/Sofia",
    flag: "🇧🇬",
  },
  {
    id: "bucharest",
    name: "ブカレスト",
    nameEn: "Bucharest",
    country: "ルーマニア",
    countryCode: "RO",
    timezone: "Europe/Bucharest",
    flag: "🇷🇴",
  },
  {
    id: "chisinau",
    name: "キシナウ",
    nameEn: "Chisinau",
    country: "モルドバ",
    countryCode: "MD",
    timezone: "Europe/Chisinau",
    flag: "🇲🇩",
  },

  // Nordic & Baltic
  {
    id: "stockholm",
    name: "ストックホルム",
    nameEn: "Stockholm",
    country: "スウェーデン",
    countryCode: "SE",
    timezone: "Europe/Stockholm",
    flag: "🇸🇪",
  },
  {
    id: "gothenburg",
    name: "ヨーテボリ",
    nameEn: "Gothenburg",
    country: "スウェーデン",
    countryCode: "SE",
    timezone: "Europe/Stockholm",
    flag: "🇸🇪",
  },
  {
    id: "oslo",
    name: "オスロ",
    nameEn: "Oslo",
    country: "ノルウェー",
    countryCode: "NO",
    timezone: "Europe/Oslo",
    flag: "🇳🇴",
  },
  {
    id: "bergen",
    name: "ベルゲン",
    nameEn: "Bergen",
    country: "ノルウェー",
    countryCode: "NO",
    timezone: "Europe/Oslo",
    flag: "🇳🇴",
  },
  {
    id: "copenhagen",
    name: "コペンハーゲン",
    nameEn: "Copenhagen",
    country: "デンマーク",
    countryCode: "DK",
    timezone: "Europe/Copenhagen",
    flag: "🇩🇰",
  },
  {
    id: "helsinki",
    name: "ヘルシンキ",
    nameEn: "Helsinki",
    country: "フィンランド",
    countryCode: "FI",
    timezone: "Europe/Helsinki",
    flag: "🇫🇮",
  },
  {
    id: "reykjavik",
    name: "レイキャビク",
    nameEn: "Reykjavik",
    country: "アイスランド",
    countryCode: "IS",
    timezone: "Atlantic/Reykjavik",
    flag: "🇮🇸",
  },
  {
    id: "tallinn",
    name: "タリン",
    nameEn: "Tallinn",
    country: "エストニア",
    countryCode: "EE",
    timezone: "Europe/Tallinn",
    flag: "🇪🇪",
  },
  {
    id: "riga",
    name: "リガ",
    nameEn: "Riga",
    country: "ラトビア",
    countryCode: "LV",
    timezone: "Europe/Riga",
    flag: "🇱🇻",
  },
  {
    id: "vilnius",
    name: "ビリニュス",
    nameEn: "Vilnius",
    country: "リトアニア",
    countryCode: "LT",
    timezone: "Europe/Vilnius",
    flag: "🇱🇹",
  },

  // Eastern Europe
  {
    id: "moscow",
    name: "モスクワ",
    nameEn: "Moscow",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Europe/Moscow",
    flag: "🇷🇺",
  },
  {
    id: "st-petersburg",
    name: "サンクトペテルブルク",
    nameEn: "St. Petersburg",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Europe/Moscow",
    flag: "🇷🇺",
  },
  {
    id: "novosibirsk",
    name: "ノヴォシビルスク",
    nameEn: "Novosibirsk",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Asia/Novosibirsk",
    flag: "🇷🇺",
  },
  {
    id: "yekaterinburg",
    name: "エカテリンブルク",
    nameEn: "Yekaterinburg",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Asia/Yekaterinburg",
    flag: "🇷🇺",
  },
  {
    id: "vladivostok",
    name: "ウラジオストク",
    nameEn: "Vladivostok",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Asia/Vladivostok",
    flag: "🇷🇺",
  },
  {
    id: "irkutsk",
    name: "イルクーツク",
    nameEn: "Irkutsk",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Asia/Irkutsk",
    flag: "🇷🇺",
  },
  {
    id: "kaliningrad",
    name: "カリーニングラード",
    nameEn: "Kaliningrad",
    country: "ロシア",
    countryCode: "RU",
    timezone: "Europe/Kaliningrad",
    flag: "🇷🇺",
  },
  {
    id: "kyiv",
    name: "キーウ",
    nameEn: "Kyiv",
    country: "ウクライナ",
    countryCode: "UA",
    timezone: "Europe/Kyiv",
    flag: "🇺🇦",
  },
  {
    id: "kharkiv",
    name: "ハルキウ",
    nameEn: "Kharkiv",
    country: "ウクライナ",
    countryCode: "UA",
    timezone: "Europe/Kyiv",
    flag: "🇺🇦",
  },
  {
    id: "odesa",
    name: "オデーサ",
    nameEn: "Odesa",
    country: "ウクライナ",
    countryCode: "UA",
    timezone: "Europe/Kyiv",
    flag: "🇺🇦",
  },
  {
    id: "minsk",
    name: "ミンスク",
    nameEn: "Minsk",
    country: "ベラルーシ",
    countryCode: "BY",
    timezone: "Europe/Minsk",
    flag: "🇧🇾",
  },

  // Turkey
  {
    id: "istanbul",
    name: "イスタンブール",
    nameEn: "Istanbul",
    country: "トルコ",
    countryCode: "TR",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
  },
  {
    id: "ankara",
    name: "アンカラ",
    nameEn: "Ankara",
    country: "トルコ",
    countryCode: "TR",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
  },
  {
    id: "izmir",
    name: "イズミール",
    nameEn: "Izmir",
    country: "トルコ",
    countryCode: "TR",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
  },
  {
    id: "antalya",
    name: "アンタルヤ",
    nameEn: "Antalya",
    country: "トルコ",
    countryCode: "TR",
    timezone: "Europe/Istanbul",
    flag: "🇹🇷",
  },

  // ===== AFRICA =====
  // North Africa
  {
    id: "cairo",
    name: "カイロ",
    nameEn: "Cairo",
    country: "エジプト",
    countryCode: "EG",
    timezone: "Africa/Cairo",
    flag: "🇪🇬",
  },
  {
    id: "alexandria",
    name: "アレクサンドリア",
    nameEn: "Alexandria",
    country: "エジプト",
    countryCode: "EG",
    timezone: "Africa/Cairo",
    flag: "🇪🇬",
  },
  {
    id: "casablanca",
    name: "カサブランカ",
    nameEn: "Casablanca",
    country: "モロッコ",
    countryCode: "MA",
    timezone: "Africa/Casablanca",
    flag: "🇲🇦",
  },
  {
    id: "marrakech",
    name: "マラケシュ",
    nameEn: "Marrakech",
    country: "モロッコ",
    countryCode: "MA",
    timezone: "Africa/Casablanca",
    flag: "🇲🇦",
  },
  {
    id: "rabat",
    name: "ラバト",
    nameEn: "Rabat",
    country: "モロッコ",
    countryCode: "MA",
    timezone: "Africa/Casablanca",
    flag: "🇲🇦",
  },
  {
    id: "algiers",
    name: "アルジェ",
    nameEn: "Algiers",
    country: "アルジェリア",
    countryCode: "DZ",
    timezone: "Africa/Algiers",
    flag: "🇩🇿",
  },
  {
    id: "tunis",
    name: "チュニス",
    nameEn: "Tunis",
    country: "チュニジア",
    countryCode: "TN",
    timezone: "Africa/Tunis",
    flag: "🇹🇳",
  },
  {
    id: "tripoli",
    name: "トリポリ",
    nameEn: "Tripoli",
    country: "リビア",
    countryCode: "LY",
    timezone: "Africa/Tripoli",
    flag: "🇱🇾",
  },
  {
    id: "khartoum",
    name: "ハルツーム",
    nameEn: "Khartoum",
    country: "スーダン",
    countryCode: "SD",
    timezone: "Africa/Khartoum",
    flag: "🇸🇩",
  },

  // West Africa
  {
    id: "lagos",
    name: "ラゴス",
    nameEn: "Lagos",
    country: "ナイジェリア",
    countryCode: "NG",
    timezone: "Africa/Lagos",
    flag: "🇳🇬",
  },
  {
    id: "abuja",
    name: "アブジャ",
    nameEn: "Abuja",
    country: "ナイジェリア",
    countryCode: "NG",
    timezone: "Africa/Lagos",
    flag: "🇳🇬",
  },
  {
    id: "accra",
    name: "アクラ",
    nameEn: "Accra",
    country: "ガーナ",
    countryCode: "GH",
    timezone: "Africa/Accra",
    flag: "🇬🇭",
  },
  {
    id: "dakar",
    name: "ダカール",
    nameEn: "Dakar",
    country: "セネガル",
    countryCode: "SN",
    timezone: "Africa/Dakar",
    flag: "🇸🇳",
  },
  {
    id: "abidjan",
    name: "アビジャン",
    nameEn: "Abidjan",
    country: "コートジボワール",
    countryCode: "CI",
    timezone: "Africa/Abidjan",
    flag: "🇨🇮",
  },
  {
    id: "bamako",
    name: "バマコ",
    nameEn: "Bamako",
    country: "マリ",
    countryCode: "ML",
    timezone: "Africa/Bamako",
    flag: "🇲🇱",
  },
  {
    id: "ouagadougou",
    name: "ワガドゥグー",
    nameEn: "Ouagadougou",
    country: "ブルキナファソ",
    countryCode: "BF",
    timezone: "Africa/Ouagadougou",
    flag: "🇧🇫",
  },
  {
    id: "niamey",
    name: "ニアメ",
    nameEn: "Niamey",
    country: "ニジェール",
    countryCode: "NE",
    timezone: "Africa/Niamey",
    flag: "🇳🇪",
  },
  {
    id: "conakry",
    name: "コナクリ",
    nameEn: "Conakry",
    country: "ギニア",
    countryCode: "GN",
    timezone: "Africa/Conakry",
    flag: "🇬🇳",
  },
  {
    id: "freetown",
    name: "フリータウン",
    nameEn: "Freetown",
    country: "シエラレオネ",
    countryCode: "SL",
    timezone: "Africa/Freetown",
    flag: "🇸🇱",
  },
  {
    id: "monrovia",
    name: "モンロビア",
    nameEn: "Monrovia",
    country: "リベリア",
    countryCode: "LR",
    timezone: "Africa/Monrovia",
    flag: "🇱🇷",
  },
  {
    id: "lome",
    name: "ロメ",
    nameEn: "Lomé",
    country: "トーゴ",
    countryCode: "TG",
    timezone: "Africa/Lome",
    flag: "🇹🇬",
  },
  {
    id: "cotonou",
    name: "コトヌー",
    nameEn: "Cotonou",
    country: "ベナン",
    countryCode: "BJ",
    timezone: "Africa/Porto-Novo",
    flag: "🇧🇯",
  },
  {
    id: "nouakchott",
    name: "ヌアクショット",
    nameEn: "Nouakchott",
    country: "モーリタニア",
    countryCode: "MR",
    timezone: "Africa/Nouakchott",
    flag: "🇲🇷",
  },
  {
    id: "banjul",
    name: "バンジュール",
    nameEn: "Banjul",
    country: "ガンビア",
    countryCode: "GM",
    timezone: "Africa/Banjul",
    flag: "🇬🇲",
  },
  {
    id: "bissau",
    name: "ビサウ",
    nameEn: "Bissau",
    country: "ギニアビサウ",
    countryCode: "GW",
    timezone: "Africa/Bissau",
    flag: "🇬🇼",
  },
  {
    id: "praia",
    name: "プライア",
    nameEn: "Praia",
    country: "カーボベルデ",
    countryCode: "CV",
    timezone: "Atlantic/Cape_Verde",
    flag: "🇨🇻",
  },

  // Central Africa
  {
    id: "kinshasa",
    name: "キンシャサ",
    nameEn: "Kinshasa",
    country: "コンゴ民主共和国",
    countryCode: "CD",
    timezone: "Africa/Kinshasa",
    flag: "🇨🇩",
  },
  {
    id: "lubumbashi",
    name: "ルブンバシ",
    nameEn: "Lubumbashi",
    country: "コンゴ民主共和国",
    countryCode: "CD",
    timezone: "Africa/Lubumbashi",
    flag: "🇨🇩",
  },
  {
    id: "brazzaville",
    name: "ブラザビル",
    nameEn: "Brazzaville",
    country: "コンゴ共和国",
    countryCode: "CG",
    timezone: "Africa/Brazzaville",
    flag: "🇨🇬",
  },
  {
    id: "yaounde",
    name: "ヤウンデ",
    nameEn: "Yaoundé",
    country: "カメルーン",
    countryCode: "CM",
    timezone: "Africa/Douala",
    flag: "🇨🇲",
  },
  {
    id: "douala",
    name: "ドゥアラ",
    nameEn: "Douala",
    country: "カメルーン",
    countryCode: "CM",
    timezone: "Africa/Douala",
    flag: "🇨🇲",
  },
  {
    id: "libreville",
    name: "リーブルビル",
    nameEn: "Libreville",
    country: "ガボン",
    countryCode: "GA",
    timezone: "Africa/Libreville",
    flag: "🇬🇦",
  },
  {
    id: "malabo",
    name: "マラボ",
    nameEn: "Malabo",
    country: "赤道ギニア",
    countryCode: "GQ",
    timezone: "Africa/Malabo",
    flag: "🇬🇶",
  },
  {
    id: "bangui",
    name: "バンギ",
    nameEn: "Bangui",
    country: "中央アフリカ",
    countryCode: "CF",
    timezone: "Africa/Bangui",
    flag: "🇨🇫",
  },
  {
    id: "ndjamena",
    name: "ンジャメナ",
    nameEn: "N'Djamena",
    country: "チャド",
    countryCode: "TD",
    timezone: "Africa/Ndjamena",
    flag: "🇹🇩",
  },
  {
    id: "sao-tome",
    name: "サントメ",
    nameEn: "São Tomé",
    country: "サントメ・プリンシペ",
    countryCode: "ST",
    timezone: "Africa/Sao_Tome",
    flag: "🇸🇹",
  },

  // East Africa
  {
    id: "nairobi",
    name: "ナイロビ",
    nameEn: "Nairobi",
    country: "ケニア",
    countryCode: "KE",
    timezone: "Africa/Nairobi",
    flag: "🇰🇪",
  },
  {
    id: "mombasa",
    name: "モンバサ",
    nameEn: "Mombasa",
    country: "ケニア",
    countryCode: "KE",
    timezone: "Africa/Nairobi",
    flag: "🇰🇪",
  },
  {
    id: "addis-ababa",
    name: "アディスアベバ",
    nameEn: "Addis Ababa",
    country: "エチオピア",
    countryCode: "ET",
    timezone: "Africa/Addis_Ababa",
    flag: "🇪🇹",
  },
  {
    id: "dar-es-salaam",
    name: "ダルエスサラーム",
    nameEn: "Dar es Salaam",
    country: "タンザニア",
    countryCode: "TZ",
    timezone: "Africa/Dar_es_Salaam",
    flag: "🇹🇿",
  },
  {
    id: "kampala",
    name: "カンパラ",
    nameEn: "Kampala",
    country: "ウガンダ",
    countryCode: "UG",
    timezone: "Africa/Kampala",
    flag: "🇺🇬",
  },
  {
    id: "kigali",
    name: "キガリ",
    nameEn: "Kigali",
    country: "ルワンダ",
    countryCode: "RW",
    timezone: "Africa/Kigali",
    flag: "🇷🇼",
  },
  {
    id: "bujumbura",
    name: "ブジュンブラ",
    nameEn: "Bujumbura",
    country: "ブルンジ",
    countryCode: "BI",
    timezone: "Africa/Bujumbura",
    flag: "🇧🇮",
  },
  {
    id: "mogadishu",
    name: "モガディシュ",
    nameEn: "Mogadishu",
    country: "ソマリア",
    countryCode: "SO",
    timezone: "Africa/Mogadishu",
    flag: "🇸🇴",
  },
  {
    id: "djibouti",
    name: "ジブチ",
    nameEn: "Djibouti",
    country: "ジブチ",
    countryCode: "DJ",
    timezone: "Africa/Djibouti",
    flag: "🇩🇯",
  },
  {
    id: "asmara",
    name: "アスマラ",
    nameEn: "Asmara",
    country: "エリトリア",
    countryCode: "ER",
    timezone: "Africa/Asmara",
    flag: "🇪🇷",
  },
  {
    id: "juba",
    name: "ジュバ",
    nameEn: "Juba",
    country: "南スーダン",
    countryCode: "SS",
    timezone: "Africa/Juba",
    flag: "🇸🇸",
  },

  // Southern Africa
  {
    id: "johannesburg",
    name: "ヨハネスブルグ",
    nameEn: "Johannesburg",
    country: "南アフリカ",
    countryCode: "ZA",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
  },
  {
    id: "cape-town",
    name: "ケープタウン",
    nameEn: "Cape Town",
    country: "南アフリカ",
    countryCode: "ZA",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
  },
  {
    id: "durban",
    name: "ダーバン",
    nameEn: "Durban",
    country: "南アフリカ",
    countryCode: "ZA",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
  },
  {
    id: "pretoria",
    name: "プレトリア",
    nameEn: "Pretoria",
    country: "南アフリカ",
    countryCode: "ZA",
    timezone: "Africa/Johannesburg",
    flag: "🇿🇦",
  },
  {
    id: "harare",
    name: "ハラレ",
    nameEn: "Harare",
    country: "ジンバブエ",
    countryCode: "ZW",
    timezone: "Africa/Harare",
    flag: "🇿🇼",
  },
  {
    id: "lusaka",
    name: "ルサカ",
    nameEn: "Lusaka",
    country: "ザンビア",
    countryCode: "ZM",
    timezone: "Africa/Lusaka",
    flag: "🇿🇲",
  },
  {
    id: "lilongwe",
    name: "リロングウェ",
    nameEn: "Lilongwe",
    country: "マラウイ",
    countryCode: "MW",
    timezone: "Africa/Blantyre",
    flag: "🇲🇼",
  },
  {
    id: "maputo",
    name: "マプト",
    nameEn: "Maputo",
    country: "モザンビーク",
    countryCode: "MZ",
    timezone: "Africa/Maputo",
    flag: "🇲🇿",
  },
  {
    id: "luanda",
    name: "ルアンダ",
    nameEn: "Luanda",
    country: "アンゴラ",
    countryCode: "AO",
    timezone: "Africa/Luanda",
    flag: "🇦🇴",
  },
  {
    id: "gaborone",
    name: "ハボローネ",
    nameEn: "Gaborone",
    country: "ボツワナ",
    countryCode: "BW",
    timezone: "Africa/Gaborone",
    flag: "🇧🇼",
  },
  {
    id: "windhoek",
    name: "ウィントフック",
    nameEn: "Windhoek",
    country: "ナミビア",
    countryCode: "NA",
    timezone: "Africa/Windhoek",
    flag: "🇳🇦",
  },
  {
    id: "mbabane",
    name: "ムババーネ",
    nameEn: "Mbabane",
    country: "エスワティニ",
    countryCode: "SZ",
    timezone: "Africa/Mbabane",
    flag: "🇸🇿",
  },
  {
    id: "maseru",
    name: "マセル",
    nameEn: "Maseru",
    country: "レソト",
    countryCode: "LS",
    timezone: "Africa/Maseru",
    flag: "🇱🇸",
  },

  // Indian Ocean (Africa)
  {
    id: "antananarivo",
    name: "アンタナナリボ",
    nameEn: "Antananarivo",
    country: "マダガスカル",
    countryCode: "MG",
    timezone: "Indian/Antananarivo",
    flag: "🇲🇬",
  },
  {
    id: "port-louis",
    name: "ポートルイス",
    nameEn: "Port Louis",
    country: "モーリシャス",
    countryCode: "MU",
    timezone: "Indian/Mauritius",
    flag: "🇲🇺",
  },
  {
    id: "victoria-seychelles",
    name: "ヴィクトリア",
    nameEn: "Victoria",
    country: "セーシェル",
    countryCode: "SC",
    timezone: "Indian/Mahe",
    flag: "🇸🇨",
  },
  {
    id: "moroni",
    name: "モロニ",
    nameEn: "Moroni",
    country: "コモロ",
    countryCode: "KM",
    timezone: "Indian/Comoro",
    flag: "🇰🇲",
  },
  {
    id: "saint-denis",
    name: "サン=ドニ",
    nameEn: "Saint-Denis",
    country: "レユニオン",
    countryCode: "RE",
    timezone: "Indian/Reunion",
    flag: "🇷🇪",
  },
  {
    id: "mamoudzou",
    name: "マムズ",
    nameEn: "Mamoudzou",
    country: "マヨット",
    countryCode: "YT",
    timezone: "Indian/Mayotte",
    flag: "🇾🇹",
  },

  // ===== NORTH AMERICA =====
  // United States
  {
    id: "new-york",
    name: "ニューヨーク",
    nameEn: "New York",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "los-angeles",
    name: "ロサンゼルス",
    nameEn: "Los Angeles",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "chicago",
    name: "シカゴ",
    nameEn: "Chicago",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "houston",
    name: "ヒューストン",
    nameEn: "Houston",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "phoenix",
    name: "フェニックス",
    nameEn: "Phoenix",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Phoenix",
    flag: "🇺🇸",
  },
  {
    id: "philadelphia",
    name: "フィラデルフィア",
    nameEn: "Philadelphia",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "san-antonio",
    name: "サンアントニオ",
    nameEn: "San Antonio",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "san-diego",
    name: "サンディエゴ",
    nameEn: "San Diego",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "dallas",
    name: "ダラス",
    nameEn: "Dallas",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "san-jose",
    name: "サンノゼ",
    nameEn: "San Jose",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "austin",
    name: "オースティン",
    nameEn: "Austin",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "san-francisco",
    name: "サンフランシスコ",
    nameEn: "San Francisco",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "seattle",
    name: "シアトル",
    nameEn: "Seattle",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "denver",
    name: "デンバー",
    nameEn: "Denver",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Denver",
    flag: "🇺🇸",
  },
  {
    id: "washington-dc",
    name: "ワシントンD.C.",
    nameEn: "Washington D.C.",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "boston",
    name: "ボストン",
    nameEn: "Boston",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "atlanta",
    name: "アトランタ",
    nameEn: "Atlanta",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "miami",
    name: "マイアミ",
    nameEn: "Miami",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/New_York",
    flag: "🇺🇸",
  },
  {
    id: "detroit",
    name: "デトロイト",
    nameEn: "Detroit",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Detroit",
    flag: "🇺🇸",
  },
  {
    id: "minneapolis",
    name: "ミネアポリス",
    nameEn: "Minneapolis",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Chicago",
    flag: "🇺🇸",
  },
  {
    id: "las-vegas",
    name: "ラスベガス",
    nameEn: "Las Vegas",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "portland",
    name: "ポートランド",
    nameEn: "Portland",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Los_Angeles",
    flag: "🇺🇸",
  },
  {
    id: "honolulu",
    name: "ホノルル",
    nameEn: "Honolulu",
    country: "アメリカ",
    countryCode: "US",
    timezone: "Pacific/Honolulu",
    flag: "🇺🇸",
  },
  {
    id: "anchorage",
    name: "アンカレッジ",
    nameEn: "Anchorage",
    country: "アメリカ",
    countryCode: "US",
    timezone: "America/Anchorage",
    flag: "🇺🇸",
  },

  // Canada
  {
    id: "toronto",
    name: "トロント",
    nameEn: "Toronto",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Toronto",
    flag: "🇨🇦",
  },
  {
    id: "montreal",
    name: "モントリオール",
    nameEn: "Montreal",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Toronto",
    flag: "🇨🇦",
  },
  {
    id: "vancouver",
    name: "バンクーバー",
    nameEn: "Vancouver",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Vancouver",
    flag: "🇨🇦",
  },
  {
    id: "calgary",
    name: "カルガリー",
    nameEn: "Calgary",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Edmonton",
    flag: "🇨🇦",
  },
  {
    id: "edmonton",
    name: "エドモントン",
    nameEn: "Edmonton",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Edmonton",
    flag: "🇨🇦",
  },
  {
    id: "ottawa",
    name: "オタワ",
    nameEn: "Ottawa",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Toronto",
    flag: "🇨🇦",
  },
  {
    id: "winnipeg",
    name: "ウィニペグ",
    nameEn: "Winnipeg",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Winnipeg",
    flag: "🇨🇦",
  },
  {
    id: "quebec-city",
    name: "ケベック・シティ",
    nameEn: "Quebec City",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Toronto",
    flag: "🇨🇦",
  },
  {
    id: "halifax",
    name: "ハリファックス",
    nameEn: "Halifax",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/Halifax",
    flag: "🇨🇦",
  },
  {
    id: "st-johns",
    name: "セントジョンズ",
    nameEn: "St. John's",
    country: "カナダ",
    countryCode: "CA",
    timezone: "America/St_Johns",
    flag: "🇨🇦",
  },

  // Mexico
  {
    id: "mexico-city",
    name: "メキシコシティ",
    nameEn: "Mexico City",
    country: "メキシコ",
    countryCode: "MX",
    timezone: "America/Mexico_City",
    flag: "🇲🇽",
  },
  {
    id: "guadalajara",
    name: "グアダラハラ",
    nameEn: "Guadalajara",
    country: "メキシコ",
    countryCode: "MX",
    timezone: "America/Mexico_City",
    flag: "🇲🇽",
  },
  {
    id: "monterrey",
    name: "モンテレイ",
    nameEn: "Monterrey",
    country: "メキシコ",
    countryCode: "MX",
    timezone: "America/Monterrey",
    flag: "🇲🇽",
  },
  {
    id: "cancun",
    name: "カンクン",
    nameEn: "Cancun",
    country: "メキシコ",
    countryCode: "MX",
    timezone: "America/Cancun",
    flag: "🇲🇽",
  },
  {
    id: "tijuana",
    name: "ティファナ",
    nameEn: "Tijuana",
    country: "メキシコ",
    countryCode: "MX",
    timezone: "America/Tijuana",
    flag: "🇲🇽",
  },

  // Central America
  {
    id: "guatemala-city",
    name: "グアテマラシティ",
    nameEn: "Guatemala City",
    country: "グアテマラ",
    countryCode: "GT",
    timezone: "America/Guatemala",
    flag: "🇬🇹",
  },
  {
    id: "san-salvador",
    name: "サンサルバドル",
    nameEn: "San Salvador",
    country: "エルサルバドル",
    countryCode: "SV",
    timezone: "America/El_Salvador",
    flag: "🇸🇻",
  },
  {
    id: "tegucigalpa",
    name: "テグシガルパ",
    nameEn: "Tegucigalpa",
    country: "ホンジュラス",
    countryCode: "HN",
    timezone: "America/Tegucigalpa",
    flag: "🇭🇳",
  },
  {
    id: "managua",
    name: "マナグア",
    nameEn: "Managua",
    country: "ニカラグア",
    countryCode: "NI",
    timezone: "America/Managua",
    flag: "🇳🇮",
  },
  {
    id: "san-jose-cr",
    name: "サンホセ",
    nameEn: "San José",
    country: "コスタリカ",
    countryCode: "CR",
    timezone: "America/Costa_Rica",
    flag: "🇨🇷",
  },
  {
    id: "panama-city",
    name: "パナマシティ",
    nameEn: "Panama City",
    country: "パナマ",
    countryCode: "PA",
    timezone: "America/Panama",
    flag: "🇵🇦",
  },
  {
    id: "belize-city",
    name: "ベリーズシティ",
    nameEn: "Belize City",
    country: "ベリーズ",
    countryCode: "BZ",
    timezone: "America/Belize",
    flag: "🇧🇿",
  },

  // Caribbean
  {
    id: "havana",
    name: "ハバナ",
    nameEn: "Havana",
    country: "キューバ",
    countryCode: "CU",
    timezone: "America/Havana",
    flag: "🇨🇺",
  },
  {
    id: "kingston",
    name: "キングストン",
    nameEn: "Kingston",
    country: "ジャマイカ",
    countryCode: "JM",
    timezone: "America/Jamaica",
    flag: "🇯🇲",
  },
  {
    id: "santo-domingo",
    name: "サントドミンゴ",
    nameEn: "Santo Domingo",
    country: "ドミニカ共和国",
    countryCode: "DO",
    timezone: "America/Santo_Domingo",
    flag: "🇩🇴",
  },
  {
    id: "port-au-prince",
    name: "ポルトープランス",
    nameEn: "Port-au-Prince",
    country: "ハイチ",
    countryCode: "HT",
    timezone: "America/Port-au-Prince",
    flag: "🇭🇹",
  },
  {
    id: "san-juan",
    name: "サンフアン",
    nameEn: "San Juan",
    country: "プエルトリコ",
    countryCode: "PR",
    timezone: "America/Puerto_Rico",
    flag: "🇵🇷",
  },
  {
    id: "nassau",
    name: "ナッソー",
    nameEn: "Nassau",
    country: "バハマ",
    countryCode: "BS",
    timezone: "America/Nassau",
    flag: "🇧🇸",
  },
  {
    id: "bridgetown",
    name: "ブリッジタウン",
    nameEn: "Bridgetown",
    country: "バルバドス",
    countryCode: "BB",
    timezone: "America/Barbados",
    flag: "🇧🇧",
  },
  {
    id: "port-of-spain",
    name: "ポートオブスペイン",
    nameEn: "Port of Spain",
    country: "トリニダード・トバゴ",
    countryCode: "TT",
    timezone: "America/Port_of_Spain",
    flag: "🇹🇹",
  },
  {
    id: "willemstad",
    name: "ウィレムスタッド",
    nameEn: "Willemstad",
    country: "キュラソー",
    countryCode: "CW",
    timezone: "America/Curacao",
    flag: "🇨🇼",
  },
  {
    id: "oranjestad",
    name: "オラニエスタッド",
    nameEn: "Oranjestad",
    country: "アルバ",
    countryCode: "AW",
    timezone: "America/Aruba",
    flag: "🇦🇼",
  },
  {
    id: "george-town",
    name: "ジョージタウン",
    nameEn: "George Town",
    country: "ケイマン諸島",
    countryCode: "KY",
    timezone: "America/Cayman",
    flag: "🇰🇾",
  },
  {
    id: "hamilton",
    name: "ハミルトン",
    nameEn: "Hamilton",
    country: "バミューダ",
    countryCode: "BM",
    timezone: "Atlantic/Bermuda",
    flag: "🇧🇲",
  },

  // ===== SOUTH AMERICA =====
  {
    id: "sao-paulo",
    name: "サンパウロ",
    nameEn: "São Paulo",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
  },
  {
    id: "rio-de-janeiro",
    name: "リオデジャネイロ",
    nameEn: "Rio de Janeiro",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
  },
  {
    id: "brasilia",
    name: "ブラジリア",
    nameEn: "Brasília",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
  },
  {
    id: "salvador",
    name: "サルバドール",
    nameEn: "Salvador",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Bahia",
    flag: "🇧🇷",
  },
  {
    id: "fortaleza",
    name: "フォルタレザ",
    nameEn: "Fortaleza",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Fortaleza",
    flag: "🇧🇷",
  },
  {
    id: "belo-horizonte",
    name: "ベロオリゾンテ",
    nameEn: "Belo Horizonte",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Sao_Paulo",
    flag: "🇧🇷",
  },
  {
    id: "manaus",
    name: "マナウス",
    nameEn: "Manaus",
    country: "ブラジル",
    countryCode: "BR",
    timezone: "America/Manaus",
    flag: "🇧🇷",
  },
  {
    id: "buenos-aires",
    name: "ブエノスアイレス",
    nameEn: "Buenos Aires",
    country: "アルゼンチン",
    countryCode: "AR",
    timezone: "America/Argentina/Buenos_Aires",
    flag: "🇦🇷",
  },
  {
    id: "cordoba",
    name: "コルドバ",
    nameEn: "Córdoba",
    country: "アルゼンチン",
    countryCode: "AR",
    timezone: "America/Argentina/Cordoba",
    flag: "🇦🇷",
  },
  {
    id: "mendoza",
    name: "メンドーサ",
    nameEn: "Mendoza",
    country: "アルゼンチン",
    countryCode: "AR",
    timezone: "America/Argentina/Mendoza",
    flag: "🇦🇷",
  },
  {
    id: "santiago",
    name: "サンティアゴ",
    nameEn: "Santiago",
    country: "チリ",
    countryCode: "CL",
    timezone: "America/Santiago",
    flag: "🇨🇱",
  },
  {
    id: "valparaiso",
    name: "バルパライソ",
    nameEn: "Valparaíso",
    country: "チリ",
    countryCode: "CL",
    timezone: "America/Santiago",
    flag: "🇨🇱",
  },
  {
    id: "lima",
    name: "リマ",
    nameEn: "Lima",
    country: "ペルー",
    countryCode: "PE",
    timezone: "America/Lima",
    flag: "🇵🇪",
  },
  {
    id: "cusco",
    name: "クスコ",
    nameEn: "Cusco",
    country: "ペルー",
    countryCode: "PE",
    timezone: "America/Lima",
    flag: "🇵🇪",
  },
  {
    id: "bogota",
    name: "ボゴタ",
    nameEn: "Bogotá",
    country: "コロンビア",
    countryCode: "CO",
    timezone: "America/Bogota",
    flag: "🇨🇴",
  },
  {
    id: "medellin",
    name: "メデジン",
    nameEn: "Medellín",
    country: "コロンビア",
    countryCode: "CO",
    timezone: "America/Bogota",
    flag: "🇨🇴",
  },
  {
    id: "cartagena",
    name: "カルタヘナ",
    nameEn: "Cartagena",
    country: "コロンビア",
    countryCode: "CO",
    timezone: "America/Bogota",
    flag: "🇨🇴",
  },
  {
    id: "caracas",
    name: "カラカス",
    nameEn: "Caracas",
    country: "ベネズエラ",
    countryCode: "VE",
    timezone: "America/Caracas",
    flag: "🇻🇪",
  },
  {
    id: "quito",
    name: "キト",
    nameEn: "Quito",
    country: "エクアドル",
    countryCode: "EC",
    timezone: "America/Guayaquil",
    flag: "🇪🇨",
  },
  {
    id: "guayaquil",
    name: "グアヤキル",
    nameEn: "Guayaquil",
    country: "エクアドル",
    countryCode: "EC",
    timezone: "America/Guayaquil",
    flag: "🇪🇨",
  },
  {
    id: "galapagos",
    name: "ガラパゴス",
    nameEn: "Galápagos",
    country: "エクアドル",
    countryCode: "EC",
    timezone: "Pacific/Galapagos",
    flag: "🇪🇨",
  },
  {
    id: "la-paz",
    name: "ラパス",
    nameEn: "La Paz",
    country: "ボリビア",
    countryCode: "BO",
    timezone: "America/La_Paz",
    flag: "🇧🇴",
  },
  {
    id: "santa-cruz",
    name: "サンタクルス",
    nameEn: "Santa Cruz",
    country: "ボリビア",
    countryCode: "BO",
    timezone: "America/La_Paz",
    flag: "🇧🇴",
  },
  {
    id: "asuncion",
    name: "アスンシオン",
    nameEn: "Asunción",
    country: "パラグアイ",
    countryCode: "PY",
    timezone: "America/Asuncion",
    flag: "🇵🇾",
  },
  {
    id: "montevideo",
    name: "モンテビデオ",
    nameEn: "Montevideo",
    country: "ウルグアイ",
    countryCode: "UY",
    timezone: "America/Montevideo",
    flag: "🇺🇾",
  },
  {
    id: "georgetown",
    name: "ジョージタウン",
    nameEn: "Georgetown",
    country: "ガイアナ",
    countryCode: "GY",
    timezone: "America/Guyana",
    flag: "🇬🇾",
  },
  {
    id: "paramaribo",
    name: "パラマリボ",
    nameEn: "Paramaribo",
    country: "スリナム",
    countryCode: "SR",
    timezone: "America/Paramaribo",
    flag: "🇸🇷",
  },
  {
    id: "cayenne",
    name: "カイエンヌ",
    nameEn: "Cayenne",
    country: "フランス領ギアナ",
    countryCode: "GF",
    timezone: "America/Cayenne",
    flag: "🇬🇫",
  },

  // ===== OCEANIA =====
  // Australia
  {
    id: "sydney",
    name: "シドニー",
    nameEn: "Sydney",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Sydney",
    flag: "🇦🇺",
  },
  {
    id: "melbourne",
    name: "メルボルン",
    nameEn: "Melbourne",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Melbourne",
    flag: "🇦🇺",
  },
  {
    id: "brisbane",
    name: "ブリスベン",
    nameEn: "Brisbane",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Brisbane",
    flag: "🇦🇺",
  },
  {
    id: "perth",
    name: "パース",
    nameEn: "Perth",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Perth",
    flag: "🇦🇺",
  },
  {
    id: "adelaide",
    name: "アデレード",
    nameEn: "Adelaide",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Adelaide",
    flag: "🇦🇺",
  },
  {
    id: "gold-coast",
    name: "ゴールドコースト",
    nameEn: "Gold Coast",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Brisbane",
    flag: "🇦🇺",
  },
  {
    id: "canberra",
    name: "キャンベラ",
    nameEn: "Canberra",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Sydney",
    flag: "🇦🇺",
  },
  {
    id: "hobart",
    name: "ホバート",
    nameEn: "Hobart",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Hobart",
    flag: "🇦🇺",
  },
  {
    id: "darwin",
    name: "ダーウィン",
    nameEn: "Darwin",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Darwin",
    flag: "🇦🇺",
  },
  {
    id: "cairns",
    name: "ケアンズ",
    nameEn: "Cairns",
    country: "オーストラリア",
    countryCode: "AU",
    timezone: "Australia/Brisbane",
    flag: "🇦🇺",
  },

  // New Zealand
  {
    id: "auckland",
    name: "オークランド",
    nameEn: "Auckland",
    country: "ニュージーランド",
    countryCode: "NZ",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
  },
  {
    id: "wellington",
    name: "ウェリントン",
    nameEn: "Wellington",
    country: "ニュージーランド",
    countryCode: "NZ",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
  },
  {
    id: "christchurch",
    name: "クライストチャーチ",
    nameEn: "Christchurch",
    country: "ニュージーランド",
    countryCode: "NZ",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
  },
  {
    id: "queenstown",
    name: "クイーンズタウン",
    nameEn: "Queenstown",
    country: "ニュージーランド",
    countryCode: "NZ",
    timezone: "Pacific/Auckland",
    flag: "🇳🇿",
  },

  // Pacific Islands
  {
    id: "suva",
    name: "スバ",
    nameEn: "Suva",
    country: "フィジー",
    countryCode: "FJ",
    timezone: "Pacific/Fiji",
    flag: "🇫🇯",
  },
  {
    id: "port-moresby",
    name: "ポートモレスビー",
    nameEn: "Port Moresby",
    country: "パプアニューギニア",
    countryCode: "PG",
    timezone: "Pacific/Port_Moresby",
    flag: "🇵🇬",
  },
  {
    id: "honiara",
    name: "ホニアラ",
    nameEn: "Honiara",
    country: "ソロモン諸島",
    countryCode: "SB",
    timezone: "Pacific/Guadalcanal",
    flag: "🇸🇧",
  },
  {
    id: "port-vila",
    name: "ポートビラ",
    nameEn: "Port Vila",
    country: "バヌアツ",
    countryCode: "VU",
    timezone: "Pacific/Efate",
    flag: "🇻🇺",
  },
  {
    id: "noumea",
    name: "ヌメア",
    nameEn: "Nouméa",
    country: "ニューカレドニア",
    countryCode: "NC",
    timezone: "Pacific/Noumea",
    flag: "🇳🇨",
  },
  {
    id: "papeete",
    name: "パペーテ",
    nameEn: "Papeete",
    country: "フランス領ポリネシア",
    countryCode: "PF",
    timezone: "Pacific/Tahiti",
    flag: "🇵🇫",
  },
  {
    id: "apia",
    name: "アピア",
    nameEn: "Apia",
    country: "サモア",
    countryCode: "WS",
    timezone: "Pacific/Apia",
    flag: "🇼🇸",
  },
  {
    id: "nuku-alofa",
    name: "ヌクアロファ",
    nameEn: "Nuku'alofa",
    country: "トンガ",
    countryCode: "TO",
    timezone: "Pacific/Tongatapu",
    flag: "🇹🇴",
  },
  {
    id: "funafuti",
    name: "フナフティ",
    nameEn: "Funafuti",
    country: "ツバル",
    countryCode: "TV",
    timezone: "Pacific/Funafuti",
    flag: "🇹🇻",
  },
  {
    id: "tarawa",
    name: "タラワ",
    nameEn: "Tarawa",
    country: "キリバス",
    countryCode: "KI",
    timezone: "Pacific/Tarawa",
    flag: "🇰🇮",
  },
  {
    id: "majuro",
    name: "マジュロ",
    nameEn: "Majuro",
    country: "マーシャル諸島",
    countryCode: "MH",
    timezone: "Pacific/Majuro",
    flag: "🇲🇭",
  },
  {
    id: "palikir",
    name: "パリキール",
    nameEn: "Palikir",
    country: "ミクロネシア",
    countryCode: "FM",
    timezone: "Pacific/Pohnpei",
    flag: "🇫🇲",
  },
  {
    id: "koror",
    name: "コロール",
    nameEn: "Koror",
    country: "パラオ",
    countryCode: "PW",
    timezone: "Pacific/Palau",
    flag: "🇵🇼",
  },
  {
    id: "yaren",
    name: "ヤレン",
    nameEn: "Yaren",
    country: "ナウル",
    countryCode: "NR",
    timezone: "Pacific/Nauru",
    flag: "🇳🇷",
  },
  {
    id: "hagatna",
    name: "ハガッニャ",
    nameEn: "Hagåtña",
    country: "グアム",
    countryCode: "GU",
    timezone: "Pacific/Guam",
    flag: "🇬🇺",
  },
  {
    id: "saipan",
    name: "サイパン",
    nameEn: "Saipan",
    country: "北マリアナ諸島",
    countryCode: "MP",
    timezone: "Pacific/Guam",
    flag: "🇲🇵",
  },
  {
    id: "pago-pago",
    name: "パゴパゴ",
    nameEn: "Pago Pago",
    country: "アメリカ領サモア",
    countryCode: "AS",
    timezone: "Pacific/Pago_Pago",
    flag: "🇦🇸",
  },
  {
    id: "rarotonga",
    name: "ラロトンガ",
    nameEn: "Rarotonga",
    country: "クック諸島",
    countryCode: "CK",
    timezone: "Pacific/Rarotonga",
    flag: "🇨🇰",
  },
  {
    id: "alofi",
    name: "アロフィ",
    nameEn: "Alofi",
    country: "ニウエ",
    countryCode: "NU",
    timezone: "Pacific/Niue",
    flag: "🇳🇺",
  },
  {
    id: "easter-island",
    name: "イースター島",
    nameEn: "Easter Island",
    country: "チリ",
    countryCode: "CL",
    timezone: "Pacific/Easter",
    flag: "🇨🇱",
  },

  // ===== ATLANTIC =====
  {
    id: "azores",
    name: "アゾレス諸島",
    nameEn: "Azores",
    country: "ポルトガル",
    countryCode: "PT",
    timezone: "Atlantic/Azores",
    flag: "🇵🇹",
  },
  {
    id: "canary-islands",
    name: "カナリア諸島",
    nameEn: "Canary Islands",
    country: "スペイン",
    countryCode: "ES",
    timezone: "Atlantic/Canary",
    flag: "🇪🇸",
  },
  {
    id: "madeira",
    name: "マデイラ諸島",
    nameEn: "Madeira",
    country: "ポルトガル",
    countryCode: "PT",
    timezone: "Atlantic/Madeira",
    flag: "🇵🇹",
  },
  {
    id: "stanley",
    name: "スタンリー",
    nameEn: "Stanley",
    country: "フォークランド諸島",
    countryCode: "FK",
    timezone: "Atlantic/Stanley",
    flag: "🇫🇰",
  },
  {
    id: "south-georgia",
    name: "サウスジョージア",
    nameEn: "South Georgia",
    country: "サウスジョージア・サウスサンドウィッチ諸島",
    countryCode: "GS",
    timezone: "Atlantic/South_Georgia",
    flag: "🇬🇸",
  },
  {
    id: "st-helena",
    name: "セントヘレナ",
    nameEn: "Saint Helena",
    country: "セントヘレナ",
    countryCode: "SH",
    timezone: "Atlantic/St_Helena",
    flag: "🇸🇭",
  },
  {
    id: "faroe-islands",
    name: "フェロー諸島",
    nameEn: "Faroe Islands",
    country: "フェロー諸島",
    countryCode: "FO",
    timezone: "Atlantic/Faroe",
    flag: "🇫🇴",
  },

  // ===== ANTARCTICA (Research Stations) =====
  {
    id: "mcmurdo",
    name: "マクマード基地",
    nameEn: "McMurdo Station",
    country: "南極",
    countryCode: "AQ",
    timezone: "Antarctica/McMurdo",
    flag: "🇦🇶",
  },
  {
    id: "palmer",
    name: "パーマー基地",
    nameEn: "Palmer Station",
    country: "南極",
    countryCode: "AQ",
    timezone: "Antarctica/Palmer",
    flag: "🇦🇶",
  },
  {
    id: "syowa",
    name: "昭和基地",
    nameEn: "Syowa Station",
    country: "南極",
    countryCode: "AQ",
    timezone: "Antarctica/Syowa",
    flag: "🇦🇶",
  },
];

export function getCityById(id: string): City | undefined {
  return CITIES.find((city) => city.id === id);
}

export function searchCities(query: string): City[] {
  const lowerQuery = query.toLowerCase();
  return CITIES.filter(
    (city) =>
      city.name.toLowerCase().includes(lowerQuery) ||
      city.nameEn.toLowerCase().includes(lowerQuery) ||
      city.country.toLowerCase().includes(lowerQuery),
  );
}

export function getCitiesByCountryCode(countryCode: string): City[] {
  return CITIES.filter(
    (city) => city.countryCode.toLowerCase() === countryCode.toLowerCase(),
  );
}

export function getCitiesByTimezone(timezone: string): City[] {
  return CITIES.filter((city) => city.timezone === timezone);
}

export function getUniqueCountries(): {
  name: string;
  code: string;
  flag: string;
}[] {
  const countryMap = new Map<
    string,
    { name: string; code: string; flag: string }
  >();
  for (const city of CITIES) {
    if (!countryMap.has(city.countryCode)) {
      countryMap.set(city.countryCode, {
        name: city.country,
        code: city.countryCode,
        flag: city.flag,
      });
    }
  }
  return Array.from(countryMap.values()).sort((a, b) =>
    a.name.localeCompare(b.name, "ja"),
  );
}
